### ISSUE TITLE
Add new Islamic project in the website

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/islamic-project#2]

**Comment by zainulabideen1122** [comment]
Hi @fawazahmed0, I am happy to work with you, can you assign this task to me?

**Comment by fawazahmed0** [comment]
@zainulabideen1122 I have assigned this task to you, you will need to add the project in [index.html](https://github.com/fawazahmed0/islamic-project/blob/main/docs/index.html)

**Comment by zainulabideen1122** [comment]
Ok got it, Tell me one thing which type of project you want?

**Comment by fawazahmed0** [comment]
any islamic project or website, that may help others.
For example: 
https://Quran.com 
https://alim.org
https://quranenc.com
https://hadeethenc.com
https://sunnah.com
